### ISSUE TITLE
Problemas

### ISSUE THREAD

**Issue by pedroprieto** [organizacion-sesion-3-Paqui-Jimenez/plantilla-jekyll#1]
Buenas @Paquijp ,

Te comento el tema por aquí:
- Esta línea está mal:
https://github.com/organizacion-sesion-3-Paqui-Jimenez/plantilla-jekyll/blob/1059b60bf0aa5fdb302fe8def4862734fcff4b7d/_layouts/plantillablog.html#L22
Debes quitarla o no te compilará el código correctamente:
![imagen](https://user-images.githubusercontent.com/7632447/116003780-c8db7080-a5ff-11eb-9d68-d634ec9b18ef.png)
- No debes incluir todo el código HTML de nuevo:
https://github.com/organizacion-sesion-3-Paqui-Jimenez/plantilla-jekyll/blob/1059b60bf0aa5fdb302fe8def4862734fcff4b7d/_layouts/plantillablog.html#L1
En su lugar puedes basarte en la plantilla principal y añadir solo el código del listado de posts:
https://github.com/organizacion-sesion-3-Paqui-Jimenez/plantilla-jekyll/blob/1059b60bf0aa5fdb302fe8def4862734fcff4b7d/_layouts/plantillablog.html#L7
Por cierto, has puesto el código dentro de la etiqueta `<head>` en lugar del `<body>`

Un saludo y ánimo!!

**Comment by Paquijp** [comment]
Hola,
gracias he hecho los cambios, pero no me muestra el contenido dels posts, File no found

Saludos,
Paqui

**Comment by pedroprieto** [comment]
Buenas,

Te falta preceder la URL de los posts con `site.baseurl`:
https://github.com/organizacion-sesion-3-Paqui-Jimenez/plantilla-jekyll/blob/926bd5a79af3a3c328ff942ca580768fd4649a78/_layouts/plantillablog.html#L17

Debería quedar:
```html
 <a href="{{site.baseurl}}{{ post.url }}">{{ post.title }}</a> 
```

Un saludo!
